(function(){
'use strict';
const $=(s,r=document)=>r.querySelector(s),$$=(s,r=document)=>[...r.querySelectorAll(s)];
const TODAY=()=>new Date().toISOString().slice(0,10);
const S={ctx:null,view:'dashboard',data:{},busy:false,chatUnsub:null,activeChat:null,activeOther:null};
const modules=[
{id:'dashboard',name:'Dashboard',icon:'◫',always:true},
{id:'employees',name:'Employees',icon:'♙',perm:'EMPLOYEES_VIEW'},
{id:'roles',name:'Roles & Permissions',icon:'◆',perm:'ROLES_MANAGE'},
{id:'clients',name:'Work Progress',icon:'◎',perm:'CLIENTS_VIEW'},
{id:'progress',name:'Daily Progress',icon:'◒',perm:'PROGRESS_VIEW'},
{id:'attendance',name:'Attendance',icon:'◷',perm:'ATTENDANCE_VIEW'},
{id:'requests',name:'Requests',icon:'⌁',perm:'LEAVE_VIEW'},
{id:'expenses',name:'Expenses',icon:'₹',perm:'EXPENSES_VIEW'},
{id:'payroll',name:'Payroll & Payslips',icon:'♙',perm:'COMPENSATIONS_VIEW'},
{id:'invoice',name:'Invoice',icon:'▣'},
{id:'survey-reports',name:'Survey Reports',icon:'⌖'},
{id:'reports',name:'Reports',icon:'▤',perm:'REPORTS_VIEW'},
{id:'files',name:'Files',icon:'□',perm:'FILES_VIEW'},
{id:'chat',name:'Chat',icon:'◉',perm:'CHAT_VIEW'},
{id:'audit',name:'Audit Logs',icon:'◌',perm:'AUDIT_VIEW'},
{id:'settings',name:'Settings',icon:'⚙',perm:'SETTINGS_MANAGE'}
];
const expenseGroups={FLAT:['Rent / EMI','Electricity Bill','Construction Repairs','Goods for Repairs','Electrical Maintenance','Plumbing Maintenance'],OFFICE:['Wi-Fi','AC Maintenance','Inverter Maintenance','Computer Maintenance','Printer Maintenance','CCTV Surveillance','New Equipment','Food & Beverages','Travel Allowances','Hospitalities','Client Expense & Reimbursement','Goods'],SURVEY_FIELD:['Food & Beverages','Travel Allowances','Instrument Maintenance','New Equipment']};
const surveyDepartments=['SURVEY_FIELD','SURVEY_OFFICE'];
function esc(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));}
function money(v){return new Intl.NumberFormat('en-IN',{style:'currency',currency:'INR',maximumFractionDigits:2}).format(Number(v)||0)}
function toast(msg,type='success'){const el=document.createElement('div');el.className=`toast ${type}`;el.textContent=msg;$('#toastRegion')?.append(el);setTimeout(()=>el.remove(),3500)}
function errorMessage(e){const m=OfficeDB.cleanError(e);if(/permission|not allowed|policy|row-level security|authorized/i.test(m))return "You don't have permission to perform this action.";if(/JWT|session|auth/i.test(m))return 'Your session has expired. Please sign in again.';return m}
function setBusy(b){S.busy=b;document.body.classList.toggle('busy',b);$$('button').forEach(x=>{if(!x.dataset.allowBusy)x.disabled=b})}
function has(p,a){return OfficePermissions.any(p,a)}
function myDeptCodes(){return (S.ctx.departments||[]).map(d=>d.code)}
function canInvoice(){return OfficePermissions.isAdmin()||has('INVOICES_VIEW','VIEW')||has('INVOICES_ASSIGNED_VIEW','VIEW')}
function canSurveyReports(){return OfficePermissions.isAdmin()||has('SURVEY_REPORTS_VIEW','VIEW')||has('SURVEY_REPORTS_ASSIGNED_VIEW','VIEW')}
function visibleModules(){return modules.filter(m=>m.always||(m.id==='invoice'&&canInvoice())||(m.id==='survey-reports'&&canSurveyReports())||(m.perm&&(has(m.perm,'VIEW')||has(m.perm,'MANAGE'))))}
function module(id){return modules.find(m=>m.id===id)||modules[0]}
function nav(){const list=visibleModules();$('#sideNav').innerHTML=list.map(m=>`<button class="nav-item ${S.view===m.id?'active':''}" data-view="${m.id}"><span class="nav-icon">${m.icon}</span><span>${esc(m.name)}</span></button>`).join('')}
function profile(){const p=S.ctx.profile,r=S.ctx.roles.map(x=>x.name).join(' · ')||'Employee';$('#profileName').textContent=p.display_name;$('#profileRole').textContent=r;$('#avatar').textContent=(p.display_name||'A').slice(0,1).toUpperCase()}
function layout(){nav();profile();$('#crumbCurrent').textContent=module(S.view).name}
async function load(table,opts={}){S.data[table]=await OfficeDB.list(table,opts);return S.data[table]}
async function refresh(){setBusy(true);const failures=[];try{try{await OfficeDB.rpc('ensure_daily_attendance',{p_date:TODAY()})}catch(e){failures.push(`attendance initialization: ${errorMessage(e)}`)}if(new Date().getDate()===28&&!OfficePermissions.isAdmin()){try{await OfficeDB.rpc('open_attendance_revision')}catch(e){failures.push(`attendance revision initialization: ${errorMessage(e)}`)}}const tables=[['profiles','created_at'],['roles','created_at'],['permissions','created_at'],['employee_roles',null],['departments','created_at'],['employee_departments',null],['clients','created_at'],['projects','created_at'],['project_members',null],['work_assignments','created_at'],['work_types','created_at'],['daily_progress','created_at'],['attendance','attendance_date'],['leave_requests','created_at'],['holidays','holiday_date'],['attendance_settings',null],['expenses','created_at'],['expense_categories','created_at'],['compensations','compensation_month'],['files','created_at'],['invoices','created_at'],['survey_reports','report_date']];await Promise.all(tables.map(async([t,order])=>{try{await load(t,order?{order}: {})}catch(e){failures.push(`${t}: ${errorMessage(e)}`);S.data[t]=[]}}));if(OfficePermissions.isAdmin()){try{S.data.audit_logs=await load('audit_logs',{order:'occurred_at'})}catch(e){failures.push(`audit_logs: ${errorMessage(e)}`);S.data.audit_logs=[]}}await render();if(failures.length)toast(`Some data could not be loaded: ${failures.slice(0,2).join(' | ')}`,'error')}finally{setBusy(false)}}
function pageHead(title,sub,actions=''){return `<div class="page-head"><div><div class="eyebrow">OFFICELEDGER</div><h1>${esc(title)}</h1><p>${esc(sub)}</p></div><div class="page-actions">${actions}</div></div>`}
function table(headers,rows,empty='No records found'){if(!rows.length)return `<div class="empty-state"><strong>${esc(empty)}</strong><span>Nothing is available in your authorized scope.</span></div>`;return `<div class="table-scroll"><table><thead><tr>${headers.map(h=>`<th>${esc(h)}</th>`).join('')}</tr></thead><tbody>${rows.join('')}</tbody></table></div>`}
function metric(label,value,sub=''){return `<div class="metric-card"><div class="metric-label">${esc(label)}</div><div class="metric-value">${esc(value)}</div><div class="metric-foot">${esc(sub)}</div></div>`}
function moduleCard(m){return `<button class="module-card" data-view="${m.id}"><span class="module-icon">${m.icon}</span><span><strong>${esc(m.name)}</strong><small>${esc(({employees:'Employee accounts',roles:'Roles and permission scopes',clients:'Project work progress and payment status',progress:'Own or company progress tracking',attendance:'Secure daily check-in / check-out',requests:'Leave and allowance requests',expenses:'Accounting and advance requests',payroll:'Attendance-linked compensation',invoice:'Quotation and tax invoice studio','survey-reports':'Survey report studio',reports:'Operational and financial reports',files:'Private business files',chat:'Private one-to-one employee chat',audit:'Administrative audit history',settings:'Application configuration',dashboard:'Authorized workspace'}[m.id]||''))}</small></span><span class="module-arrow">→</span></button>`}
function fieldHtml(f){let c;if(f.type==='select')c=`<select name="${esc(f.name)}" ${f.required?'required':''}>${f.placeholder===false?'':'<option value="">Select…</option>'}${(f.options||[]).map(o=>{const [v,l]=Array.isArray(o)?o:[o,o];return `<option value="${esc(v)}" ${String(f.value??'')===String(v)?'selected':''}>${esc(l)}</option>`}).join('')}</select>`;else if(f.type==='textarea')c=`<textarea name="${esc(f.name)}" maxlength="${f.max||5000}" ${f.required?'required':''}>${esc(f.value||'')}</textarea>`;else c=`<input name="${esc(f.name)}" type="${esc(f.type||'text')}" value="${esc(f.value??'')}" ${f.required?'required':''} ${f.min!=null?`min="${f.min}"`:''} ${f.max!=null?`max="${f.max}"`:''} ${f.step?`step="${f.step}"`:''} maxlength="${f.maxLength||240}" ${f.list?`list="${esc(f.list)}"`:''}>${f.datalist?`<datalist id="${esc(f.list||f.name+'List')}">${f.datalist.map(x=>`<option value="${esc(x)}"></option>`).join('')}</datalist>`:''}`;return `<label class="field ${f.full?'full':''}">${esc(f.label)}${c}</label>`}
function formValues(fields){const o={};for(const f of fields){const e=$(`[name="${CSS.escape(f.name)}"]`);if(e)o[f.name]=e.value}return o}
function isAdminReadOnly(){return OfficePermissions.isAdmin() && !S.ctx.roles.some(r=>r.code==='ACCOUNTING')}
function canExport(){return has('REPORTS_EXPORT','EXPORT')||has('INVOICES_EXPORT','EXPORT')||has('SURVEY_REPORTS_EXPORT','EXPORT')||has('COMPENSATIONS_EXPORT','EXPORT')||has('PAYMENTS_EXPORT','EXPORT')}
function csvCell(v){return '"'+String(v??'').replace(/"/g,'""')+'"'}
function exportCsv(filename,headers,rows){const csv='\ufeff'+[headers,...rows].map(r=>r.map(csvCell).join(',')).join('\r\n');const blob=new Blob([csv],{type:'text/csv;charset=utf-8'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=filename;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000);toast(`Exported ${filename}`)}
function openDialog(title,fields,onSave){const d=$('#recordDialog');$('#recordModalTitle').textContent=title;$('#recordModalSubtitle').textContent='The server remains the source of truth and validates authorization.';$('#recordFields').innerHTML=fields.map(fieldHtml).join('');$('#recordError').hidden=true;$('#recordForm').onsubmit=async e=>{e.preventDefault();try{setBusy(true);await onSave(formValues(fields));d.close();toast('Saved successfully.');await refresh()}catch(err){$('#recordError').textContent=errorMessage(err);$('#recordError').hidden=false}finally{setBusy(false)}};d.showModal()}
async function renderDashboard(){const projects=S.data.projects||[],progress=S.data.daily_progress||[];const active=projects.filter(p=>p.status==='ACTIVE').length,pending=projects.filter(p=>!['COMPLETED','CANCELLED'].includes(p.status)).length,today=progress.filter(p=>p.progress_date===TODAY()).length;const cards=visibleModules().filter(m=>m.id!=='dashboard');$('#view').innerHTML=pageHead('Dashboard','Live Supabase-backed workspace with permission-aware cards.')+`<div class="grid four summary-grid">${metric('Active projects',active,'authorized scope')}${metric('Open projects',pending,'work status')}${metric('Today progress',today,'submitted updates')}</div><section class="module-grid">${cards.map(moduleCard).join('')}</section>`}
function renderClientsProjects(){const clients=S.data.clients||[],projects=S.data.projects||[],profiles=S.data.profiles||[],departments=S.data.departments||[];const rows=projects.map(p=>{const c=clients.find(x=>x.id===p.client_id),ab=profiles.find(x=>x.user_id===p.assigned_by),at=profiles.find(x=>x.user_id===p.assigned_to);const edit=!isAdminReadOnly()&&has('PROJECTS_EDIT','EDIT')?`<button class="btn small" data-edit-project="${esc(p.id)}">Edit</button>`:'';const dept=departments.find(d=>d.code===p.department||d.name===p.department)?.name||p.department||'—';return `<tr><td>${esc(c?.name||'—')}</td><td>${esc(c?.contact||'—')}</td><td>${esc(p.name)}</td><td>${esc(c?.location||'—')}</td><td>${esc(dept)}</td><td>${esc(at?.display_name||'—')}</td><td><span class="status">${esc(p.status||'PLANNED')}</span></td><td>${esc(p.priority||'NORMAL')}</td><td>${esc(p.payment_status||'PENDING')}</td><td>${esc(p.payment_update||'ADVANCE')}</td><td class="table-actions">${edit}</td></tr>`});const act=!isAdminReadOnly()&&has('PROJECTS_CREATE','CREATE')?'<button class="btn primary" id="addProject">＋ New project</button>':'';const exp=canExport()?'<button class="btn" id="exportProjects">Export CSV</button>':'';$('#view').innerHTML=pageHead('Work Progress','Admin tracks company-wide progress; operational editing is restricted to authorized non-admin roles.',act+exp)+`<section class="panel">${table(['Client Name','Contact','Project Name','Location','Department Handling','Assigned To','Work Status','Priority','Payment Status','Payment Update','Action'],rows)}</section>`;$('#addProject')?.addEventListener('click',()=>openProject());$('#exportProjects')?.addEventListener('click',()=>exportCsv(`officeledger-work-progress-${TODAY()}.csv`,['Client Name','Project Name','Department','Assigned To','Status','Priority','Payment Status'],projects.map(p=>{const c=clients.find(x=>x.id===p.client_id),a=profiles.find(x=>x.user_id===p.assigned_to);return[c?.name,p.name,p.department,a?.display_name,p.status,p.priority,p.payment_status]})));$$('[data-edit-project]').forEach(b=>b.addEventListener('click',()=>openProject(projects.find(p=>p.id===b.dataset.editProject))))}
async function resolveClientId(name){const clean=String(name||'').trim();if(!clean)throw new Error('Client name is required.');const existing=(S.data.clients||[]).find(c=>String(c.name||'').trim().toLowerCase()===clean.toLowerCase());if(existing)return existing.id;if(isAdminReadOnly())throw new Error('Administrators cannot create or edit clients.');const created=await OfficeDB.insert('clients',{name:clean,created_by:S.ctx.profile.user_id,updated_at:new Date().toISOString()});S.data.clients=[...(S.data.clients||[]),created];return created.id}
function openProject(record=null){if(isAdminReadOnly())return;const clients=S.data.clients||[];const fields=[{name:'client_name',label:'Client Name — type or select',required:true,value:record?(clients.find(c=>c.id===record.client_id)?.name||''):'',list:'clientNameOptions',datalist:clients.map(c=>c.name)},{name:'name',label:'Project Name',required:true,value:record?.name||''},{name:'department',label:'Department Handling',type:'select',required:true,options:(S.data.departments||[]).filter(d=>d.is_active!==false).map(d=>[d.code,d.name]),value:record?.department||''},{name:'assigned_by',label:'Assigned By',type:'select',required:true,options:(S.data.profiles||[]).filter(p=>p.is_active).map(p=>[p.user_id,p.display_name]),value:record?.assigned_by||S.ctx.profile.user_id},{name:'assigned_to',label:'Assigned To',type:'select',required:true,options:(S.data.profiles||[]).filter(p=>p.is_active).map(p=>[p.user_id,p.display_name]),value:record?.assigned_to||''},{name:'status',label:'Work Status',type:'select',required:true,options:['PLANNED','ACTIVE','ON_HOLD','COMPLETED','CANCELLED'],value:record?.status||'PLANNED'},{name:'priority',label:'Priority',type:'select',required:true,options:['LOW','NORMAL','HIGH','URGENT'],value:record?.priority||'NORMAL'},{name:'payment_status',label:'Payment Status',type:'select',required:true,options:['PENDING','PARTIALLY_PAID','PAID'],value:record?.payment_status||'PENDING'},{name:'payment_update',label:'Payment Update',type:'select',required:true,options:['ADVANCE','PARTIAL','FINAL'],value:record?.payment_update||'ADVANCE'}];openDialog(record?'Edit Work Progress Project':'New Work Progress Project',fields,async v=>{const clientId=await resolveClientId(v.client_name);const patch={client_id:clientId,name:v.name,department:v.department,assigned_to:v.assigned_to,status:v.status,priority:v.priority,payment_status:v.payment_status,payment_update:v.payment_update,updated_by:S.ctx.profile.user_id};return record?OfficeDB.update('projects',record.id,patch):OfficeDB.insert('projects',{...patch,created_by:S.ctx.profile.user_id})})}
function renderProgress(){const rows=(S.data.daily_progress||[]).map(p=>`<tr><td>${p.progress_date}</td><td>${esc((S.data.projects||[]).find(x=>x.id===p.project_id)?.name||'—')}</td><td>${Number(p.progress_percent)}%</td><td>${esc(p.completed_work||'')}</td><td>${esc(p.pending_work||'—')}</td><td>${esc(p.remarks||'—')}</td><td>${esc((S.data.profiles||[]).find(x=>x.user_id===p.employee_id)?.display_name||'—')}</td></tr>`);const act=!isAdminReadOnly()&&has('PROGRESS_CREATE','CREATE')?'<button class="btn primary" id="addProgress">＋ Submit update</button>':'';const exp=canExport()?'<button class="btn" id="exportProgress">Export CSV</button>':'';$('#view').innerHTML=pageHead('Daily Progress','Admin tracks company-wide updates; employees submit their own authorized progress.',act+exp)+`<section class="panel">${table(['Date','Project','Progress','Completed','Pending','Remarks','Employee'],rows)}</section>`;$('#addProgress')?.addEventListener('click',openProgress);$('#exportProgress')?.addEventListener('click',()=>exportCsv(`officeledger-daily-progress-${TODAY()}.csv`,['Date','Project','Progress','Completed','Pending','Remarks','Employee'],(S.data.daily_progress||[]).map(p=>[p.progress_date,((S.data.projects||[]).find(x=>x.id===p.project_id)?.name||''),`${Number(p.progress_percent)}%`,p.completed_work||'',p.pending_work||'',p.remarks||'',((S.data.profiles||[]).find(x=>x.user_id===p.employee_id)?.display_name||'')]))) }
function openProgress(record=null){if(isAdminReadOnly())return;const projects=(S.data.projects||[]).filter(p=>!['COMPLETED','CANCELLED'].includes(p.status));const fields=[{name:'project_id',label:'Project',type:'select',required:true,options:projects.map(p=>[p.id,p.name]),value:record?.project_id||''},{name:'progress_date',label:'Progress date',type:'date',required:true,value:record?.progress_date||TODAY()},{name:'progress_percent',label:'Progress %',type:'number',required:true,min:0,max:100,step:'1',value:record?.progress_percent??0},{name:'completed_work',label:'Completed work',type:'textarea',full:true,max:5000,value:record?.completed_work||''},{name:'pending_work',label:'Pending work',type:'textarea',full:true,max:5000,value:record?.pending_work||''},{name:'remarks',label:'Remarks',type:'textarea',full:true,max:5000,value:record?.remarks||''}];openDialog(record?'Edit daily progress':'Submit daily progress',fields,async v=>{const patch={project_id:v.project_id,progress_date:v.progress_date,progress_percent:Math.max(0,Math.min(100,Number(v.progress_percent)||0)),completed_work:v.completed_work||'',pending_work:v.pending_work||'',remarks:v.remarks||'',employee_id:S.ctx.profile.user_id,updated_by:S.ctx.profile.user_id};return record?OfficeDB.update('daily_progress',record.id,patch):OfficeDB.insert('daily_progress',patch)})}

function isAttendanceRevisionDay(){return new Date().getDate()===28}
function renderAttendance(){
 const all=S.data.attendance||[], uid=S.ctx.profile.user_id, revision=isAttendanceRevisionDay(), admin=OfficePermissions.isAdmin();
 const mineToday=all.find(a=>a.employee_id===uid&&a.attendance_date===TODAY());
 const own=admin?all:all.filter(a=>a.employee_id===uid);
 const rows=own.map(a=>{const p=(S.data.profiles||[]).find(x=>x.user_id===a.employee_id);const canRev=!admin&&revision&&a.employee_id===uid&&a.attendance_date<TODAY();const edit=canRev?`<button class="btn small" data-edit-attendance="${esc(a.id)}">Revise</button>`:'';return `<tr><td>${a.attendance_date}</td><td>${esc(p?.display_name||'—')}</td><td>${a.check_in?new Date(a.check_in).toLocaleString():'—'}</td><td>${a.check_out?new Date(a.check_out).toLocaleString():'—'}</td><td>${esc(a.mode||'—')}</td><td><span class="status ${String(a.status||'').toLowerCase()}">${esc(a.status)}</span></td><td>${Number(a.worked_minutes||0)} min</td><td>${Number(a.late_minutes||0)} min</td><td>${a.is_working_day?'Working':'Non-working'}</td><td>${edit}</td></tr>`});
 let act='';if(!mineToday&&has('ATTENDANCE_CREATE','CREATE'))act='<button class="btn primary" id="checkIn">CHECK IN</button>';else if(mineToday&&mineToday.status==='ABSENT'&&!mineToday.check_out&&has('ATTENDANCE_CREATE','CREATE'))act='<button class="btn primary" id="checkIn">CHECK IN</button>';else if(mineToday&&!mineToday.check_out&&has('ATTENDANCE_EDIT','EDIT'))act='<button class="btn primary" id="checkOut">CHECK OUT</button>';
 const settings=(S.data.attendance_settings||[])[0]||{};const today=mineToday||{};
 const notice=revision&&!admin?'<div class="callout"><strong>Monthly attendance revision is OPEN today (28th).</strong> You can revise your forgotten attendance entries for this month. Historical revision entries are recorded as employee corrections and remain auditable.</div>':'';
 const adminNote=admin?'<div class="callout"><strong>Admin view:</strong> company-wide attendance tracking only. Historical attendance editing is restricted to the employee revision window.</div>':'';
 const attendanceExport=canExport()?'<button class="btn" id="exportAttendance">Export CSV</button>':'';$('#view').innerHTML=pageHead('Attendance',`Default is ABSENT. Check-in is classified automatically as OFFICE when the server sees the configured office network; all other networks are OUTDOOR. Elapsed time is calculated from exact timestamps 24/7. Office hours ${settings.office_start||'09:30'}–${settings.office_end||'18:30'}.`,act+attendanceExport)+notice+adminNote+`<div class="grid four summary-grid">${metric('Today status',today.status||'ABSENT','automatic')}${metric('Worked time',`${Number(today.worked_minutes||0)} min`,'exact elapsed time')}${metric('Late time',`${Number(today.late_minutes||0)} min`,'vs office start')}${metric('Day',today.is_sunday?'Sunday':today.is_holiday?'Holiday':today.is_working_day?'Working day':'Non-working','calendar')}</div><section class="panel">${table(['Date','Employee','Check in','Check out','Mode','Status','Worked','Late','Day','Action'],rows)}</section>`;
 $('#checkIn')?.addEventListener('click',async()=>{try{setBusy(true);await OfficeDB.insert('attendance',{employee_id:uid,attendance_date:TODAY()});toast('Attendance marked.');await refresh()}catch(e){toast(errorMessage(e),'error')}finally{setBusy(false)}});
 $('#checkOut')?.addEventListener('click',async()=>{try{setBusy(true);await OfficeDB.update('attendance',mineToday.id,{check_out:new Date().toISOString()});toast('Checked out.');await refresh()}catch(e){toast(errorMessage(e),'error')}finally{setBusy(false)}});
 $$('[data-edit-attendance]').forEach(b=>b.addEventListener('click',()=>{const row=all.find(a=>a.id===b.dataset.editAttendance);if(row)openAttendanceRevision(row)}));$('#exportAttendance')?.addEventListener('click',()=>exportCsv(`officeledger-attendance-${TODAY()}.csv`,['Date','Employee','Check in','Check out','Mode','Status','Worked minutes','Late minutes'],own.map(a=>{const p=(S.data.profiles||[]).find(x=>x.user_id===a.employee_id);return[a.attendance_date,p?.display_name||'',a.check_in||'',a.check_out||'',a.mode||'',a.status||'',a.worked_minutes||0,a.late_minutes||0]})));
}
function openAttendanceRevision(record){if(!isAttendanceRevisionDay()||record.employee_id!==S.ctx.profile.user_id)return;const fields=[{name:'attendance_date',label:'Attendance date',type:'date',required:true,value:record.attendance_date},{name:'check_in',label:'Check-in time',type:'datetime-local',value:record.check_in?new Date(record.check_in).toISOString().slice(0,16):''},{name:'check_out',label:'Check-out time',type:'datetime-local',value:record.check_out?new Date(record.check_out).toISOString().slice(0,16):''},{name:'attendance_note',label:'Revision note',type:'textarea',required:true,value:record.attendance_note||''}];openDialog(`Revise attendance · ${record.attendance_date}`,fields,async v=>OfficeDB.rpc('submit_attendance_revision',{p_attendance_id:record.id,p_check_in:v.check_in||null,p_check_out:v.check_out||null,p_note:v.attendance_note||''}))}

function renderRequests(){const leaves=S.data.leave_requests||[];const rows=leaves.map(r=>`<tr><td>Leave</td><td>${r.leave_date}</td><td>${esc(r.leave_type)}</td><td>${esc(r.reason||'—')}</td><td><span class="status ${String(r.status||'').toLowerCase()}">${esc(r.status)}</span></td><td>${(!isAdminReadOnly()&&r.employee_id===S.ctx.profile.user_id&&r.status==='PENDING')?`<button class="btn small" data-edit-leave="${r.id}">Edit</button>`:''}${OfficePermissions.isAdmin()&&r.status==='PENDING'&&has('LEAVE_APPROVE','APPROVE')?` <button class="btn small" data-approve="${r.id}" data-status="APPROVED">Approve</button> <button class="btn small" data-approve="${r.id}" data-status="REJECTED">Reject</button>`:''}</td></tr>`);const act=has('LEAVE_CREATE','CREATE')?'<button class="btn primary" id="leaveBtn">＋ Leave request</button>':'';$('#view').innerHTML=pageHead('Requests','Employees submit their own leave. Admin can track and approve/reject requests; request fields remain read-only.',act)+`<section class="panel">${table(['Type','Date','Category','Reason','Status','Action'],rows)}</section>`;$('#leaveBtn')?.addEventListener('click',openLeave);$$('[data-edit-leave]').forEach(b=>b.addEventListener('click',()=>{const r=leaves.find(x=>x.id===b.dataset.editLeave);if(r)openLeave(r)}));$$('[data-approve]').forEach(b=>b.addEventListener('click',async()=>{try{setBusy(true);await OfficeDB.update('leave_requests',b.dataset.approve,{status:b.dataset.status,approved_by:S.ctx.profile.user_id,approved_at:new Date().toISOString()});toast('Request updated.');await refresh()}catch(e){toast(errorMessage(e),'error')}finally{setBusy(false)}}))}
function openLeave(record=null){const admin=OfficePermissions.isAdmin();if(admin&&!record)return;if(admin&&record&&isAdminReadOnly()&& !has('LEAVE_EDIT','EDIT','COMPANY')){const fields=[{name:'status',label:'Status',type:'select',required:true,options:['PENDING','APPROVED','REJECTED'],value:record?.status||'PENDING'}];openDialog('Update leave status',fields,async v=>OfficeDB.update('leave_requests',record.id,{status:v.status,approved_by:v.status==='PENDING'?null:S.ctx.profile.user_id,approved_at:v.status==='PENDING'?null:new Date().toISOString()}));return}const fields=[{name:'leave_date',label:'Leave date',type:'date',required:true,value:record?.leave_date||''},{name:'leave_type',label:'Leave type',type:'select',required:true,options:['CASUAL','SICK','PERSONAL','OTHER'],value:record?.leave_type||'CASUAL'},{name:'reason',label:'Reason',type:'textarea',full:true,value:record?.reason||''}];if(admin)fields.push({name:'status',label:'Status',type:'select',required:true,options:['PENDING','APPROVED','REJECTED'],value:record?.status||'PENDING'});openDialog(record?'Edit leave request':'Leave request',fields,async v=>{if(record){const patch={leave_date:v.leave_date,leave_type:v.leave_type,reason:v.reason};if(admin){patch.status=v.status;patch.approved_by=v.status==='PENDING'?null:S.ctx.profile.user_id;patch.approved_at=v.status==='PENDING'?null:new Date().toISOString()}return OfficeDB.update('leave_requests',record.id,patch)}return OfficeDB.insert('leave_requests',{...v,employee_id:S.ctx.profile.user_id,requested_by:S.ctx.profile.user_id,status:'PENDING'})})}
function renderExpenses(){if(!has('EXPENSES_VIEW','VIEW'))return showView('dashboard');const rows=(S.data.expenses||[]).map(e=>`<tr><td>${e.expense_date}</td><td>${esc(e.expense_group)}</td><td>${esc(e.category)}</td><td>${e.request_type==='ADVANCE_REQUEST'?'Advance request':'Expense'}</td><td class="money">${money(e.amount)}</td><td>${esc(e.status)}</td></tr>`);const act=has('EXPENSES_CREATE','CREATE')?'<button class="btn primary" id="expenseBtn">＋ Add</button>':'';$('#view').innerHTML=pageHead('Expenses','Accounting manages company expenses. Lead/Associate may submit their own permitted advance/allowance requests. Admin does not manage or track expenses.',act)+`<section class="panel">${table(['Date','Group','Category','Type','Amount','Status'],rows)}</section>`;$('#expenseBtn')?.addEventListener('click',openExpense)}
function openExpense(){const roleCodes=S.ctx.roles.map(r=>r.code);const limited=!roleCodes.includes('ACCOUNTING');const cats=limited?['Food & Beverages','Travel Allowances']:Object.values(expenseGroups).flat();const fields=[{name:'expense_group',label:'Expense group',type:'select',required:true,options:limited?['OFFICE']:['FLAT','OFFICE','SURVEY_FIELD']},{name:'category',label:'Category',type:'select',required:true,options:[...new Set(cats)]},{name:'expense_date',label:'Date',type:'date',required:true,value:TODAY()},{name:'amount',label:'Amount',type:'number',required:true,min:0,step:'0.01'},{name:'payment_method',label:'Payment method'},{name:'vendor',label:'Vendor'},{name:'description',label:'Details',type:'textarea',full:true}];openDialog(limited?'Advance / Allowance request':'New expense',fields,async v=>OfficeDB.insert('expenses',{...v,amount:Number(v.amount),created_by:S.ctx.profile.user_id,request_type:limited?'ADVANCE_REQUEST':'EXPENSE'}))}
function renderPayroll(){const rows=(S.data.compensations||[]).map(c=>`<tr><td>${c.compensation_month}</td><td>${esc((S.data.profiles||[]).find(p=>p.user_id===c.employee_id)?.display_name||'—')}</td><td>${esc(c.compensation_group)}</td><td class="money">${money(c.amount)}</td><td>${esc(c.status)}</td></tr>`);$('#view').innerHTML=pageHead('Payroll & Payslips','Compensation records are linked to attendance and database calculations.')+`<section class="panel">${table(['Month','Employee','Group','Amount','Status'],rows)}</section>`}
function renderFiles(){const rows=(S.data.files||[]).filter(f=>!f.deleted_at).map(f=>`<tr><td>${esc(f.file_name)}</td><td>${esc(f.record_type||'Project file')}</td><td>${new Date(f.created_at).toLocaleString()}</td><td><button class="btn small" data-file="${esc(f.storage_path)}" data-name="${esc(f.file_name)}">Download</button></td></tr>`);const act=has('FILES_UPLOAD','UPLOAD')||has('FILES_CREATE','CREATE')?'<button class="btn primary" id="fileBtn">＋ Upload</button>':'';$('#view').innerHTML=pageHead('Files','Private Supabase Storage with scoped metadata, sharing and version support.',act)+`<section class="panel">${table(['File','Context','Uploaded','Action'],rows)}</section>`;$('#fileBtn')?.addEventListener('click',uploadFile);$$('[data-file]').forEach(b=>b.addEventListener('click',async()=>{try{const blob=await OfficeDB.download(b.dataset.file);const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=b.dataset.name||'download';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}catch(e){toast(errorMessage(e),'error')}}))}
function uploadFile(){const input=document.createElement('input');input.type='file';input.accept='*/*';input.onchange=async()=>{const file=input.files?.[0];if(!file)return;try{setBusy(true);if(file.size>25*1024*1024)throw new Error('Maximum file size is 25 MB.');const safe=file.name.replace(/[^a-zA-Z0-9._-]/g,'_');const path=`files/${S.ctx.profile.user_id}/${crypto.randomUUID()}-${safe}`;await OfficeDB.upload(file,path);try{await OfficeDB.insert('files',{uploaded_by:S.ctx.profile.user_id,storage_path:path,file_name:file.name,mime_type:file.type||'application/octet-stream',size_bytes:file.size,bucket:OfficeDB.BUCKET,extension:(file.name.split('.').pop()||'').toLowerCase(),visibility:'CONTEXT',version:1})}catch(e){try{await OfficeDB.removeFile(path)}catch{}throw e}toast('File uploaded.');await refresh()}catch(e){toast(errorMessage(e),'error')}finally{setBusy(false)}};input.click()}
async function renderChat(){if(!has('CHAT_VIEW','VIEW')&&!OfficePermissions.isAdmin())return showView('dashboard');if(S.chatUnsub){S.chatUnsub();S.chatUnsub=null}const uid=S.ctx.profile.user_id;const conversations=await OfficeDB.list('direct_conversations',{order:'last_message_at'});const visible=conversations.filter(c=>c.user_one===uid||c.user_two===uid);const others=(S.data.profiles||[]).filter(p=>p.user_id!==uid&&p.is_active);const rows=visible.map(c=>{const oid=c.user_one===uid?c.user_two:c.user_one;const other=others.find(p=>p.user_id===oid)||(S.data.profiles||[]).find(p=>p.user_id===oid);return `<button class="chat-row" data-chat="${c.id}" data-other="${oid}"><span class="avatar">${esc((other?.display_name||'?').slice(0,1).toUpperCase())}</span><span><strong>${esc(other?.display_name||'Private chat')}</strong><small>${c.last_message_at?new Date(c.last_message_at).toLocaleString():'No messages yet'}</small></span></button>`}).join('');$('#view').innerHTML=pageHead('Chat','Private one-to-one communication. Database RLS restricts conversations and messages to participants.',`<button class="btn primary" id="newChat">＋ New private chat</button>`)+`<section class="chat-shell panel"><aside class="chat-list">${rows||'<div class="empty-state"><strong>No private chats yet</strong><span>Start a conversation with an authorized employee.</span></div>'}</aside><section class="chat-panel" id="chatPanel"><div class="chat-placeholder"><strong>Select a conversation</strong><span>Only the two participants can access these messages.</span></div></section></section>`;$('#newChat').onclick=()=>openNewChat(others);$$('[data-chat]').forEach(b=>b.onclick=()=>openConversation(b.dataset.chat,b.dataset.other));S.chatUnsub=OfficeDB.subscribe('direct_messages','INSERT',payload=>{if(S.view==='chat'&&S.activeChat&&payload.new?.conversation_id===S.activeChat)openConversation(S.activeChat,S.activeOther)} )}
async function openNewChat(others){const fields=[{name:'other',label:'Employee',type:'select',required:true,options:others.map(x=>[x.user_id,x.display_name])}];openDialog('New private chat',fields,async v=>{const a=S.ctx.profile.user_id,b=v.other;const userOne=a<b?a:b,userTwo=a<b?b:a;const existing=(await OfficeDB.list('direct_conversations')).find(c=>c.user_one===userOne&&c.user_two===userTwo);if(existing){await openConversation(existing.id,b);return}await OfficeDB.insert('direct_conversations',{user_one:userOne,user_two:userTwo});await renderChat()})}
async function openConversation(cid,otherId){const uid=S.ctx.profile.user_id;S.activeChat=cid;S.activeOther=otherId;const msgs=await OfficeDB.list('direct_messages',{eq:{conversation_id:cid},order:'sent_at',ascending:true});const other=(S.data.profiles||[]).find(p=>p.user_id===otherId);$('#chatPanel').innerHTML=`<div class="chat-head"><div class="avatar">${esc((other?.display_name||'?').slice(0,1).toUpperCase())}</div><div><strong>${esc(other?.display_name||'Private chat')}</strong><small>Participant-only access</small></div></div><div class="chat-messages" id="chatMessages">${msgs.map(m=>`<div class="chat-bubble ${m.sender_id===uid?'mine':''}"><div>${esc(m.deleted_at?'Message deleted':m.body)}</div><small>${new Date(m.sent_at).toLocaleString()}${m.read_at?' · Read':''}</small></div>`).join('')||'<div class="empty-state">No messages yet.</div>'}</div><form id="chatComposer" class="chat-composer"><textarea name="body" maxlength="5000" placeholder="Write a private message…"></textarea><input name="attachment" type="file" aria-label="Attach private file"><button class="btn primary" type="submit">Send</button></form>`;$('#chatComposer').onsubmit=async e=>{e.preventDefault();const fd=new FormData(e.currentTarget),body=String(fd.get('body')||'').trim(),file=e.currentTarget.attachment.files?.[0];if(!body&&!file)return;try{setBusy(true);const msg=await OfficeDB.insert('direct_messages',{conversation_id:cid,sender_id:uid,body:body||'Attachment'});if(file){if(file.size>25*1024*1024)throw new Error('Maximum attachment size is 25 MB.');const safe=file.name.replace(/[^a-zA-Z0-9._-]/g,'_'),path=`direct/${cid}/${crypto.randomUUID()}-${safe}`;await OfficeDB.upload(file,path);try{await OfficeDB.insert('direct_message_attachments',{message_id:msg.id,uploaded_by:uid,storage_path:path,file_name:file.name,mime_type:file.type||'application/octet-stream',size_bytes:file.size})}catch(e){try{await OfficeDB.removeFile(path)}catch{}throw e}};e.currentTarget.reset();await openConversation(cid,otherId)}catch(e){toast(errorMessage(e),'error')}finally{setBusy(false)}};$('#chatMessages').scrollTop=$('#chatMessages').scrollHeight}
function employeeOptions(includeBlank=true){return (includeBlank?[['','Not assigned — creator only']]:[]).concat((S.data.profiles||[]).filter(p=>p.is_active).map(p=>[p.user_id,p.display_name]))}
async function saveInvoice(){const frame=$('#view iframe[title="Invoice Studio"]');const state=frame?.contentWindow?.SAGT_EXPORT_STATE?.();if(!state)throw new Error('Invoice editor is not ready.');if(!['invoice','quotation'].includes(String(state.type||'')))throw new Error('Unsupported document type.');if(!String(state.number||'').trim())throw new Error('Document number is required.');const clientName=String(state.client||'').replace(/[,\n]+$/,'').trim();const client=(S.data.clients||[]).find(c=>String(c.name||'').trim().toLowerCase()===clientName.toLowerCase());const row={document_type:String(state.type)==='quotation'?'QUOTATION':'TAX_INVOICE',document_number:String(state.number).trim(),document_date:/^\d{4}-\d{2}-\d{2}$/.test(String(state.date||''))?state.date:TODAY(),payload:state,client_id:client?.id||null,created_by:S.ctx.profile.user_id,updated_by:S.ctx.profile.user_id};setBusy(true);try{await OfficeDB.insert('invoices',row);toast('Invoice / quotation saved to Supabase.');await refresh()}catch(e){toast(errorMessage(e),'error')}finally{setBusy(false)}}
async function assignInvoice(id){if(!OfficePermissions.isAdmin())return;const assignee=$('#invoiceAssignee')?.value||null;try{setBusy(true);await OfficeDB.update('invoices',id,{assigned_to:assignee,updated_by:S.ctx.profile.user_id});toast('Invoice access updated.');await refresh()}catch(e){toast(errorMessage(e),'error')}finally{setBusy(false)}}
async function saveSurvey(){const frame=$('#view iframe[title="Survey Report Studio"]');const state=frame?.contentWindow?.SAGT_EXPORT_STATE?.();if(!state?.data)throw new Error('Survey report editor is not ready.');const d=state.data;if(!String(d.documentNo||'').trim()||!String(d.reportNo||'').trim())throw new Error('Document No. and Report No. are required.');const row={report_number:String(d.reportNo).trim(),report_date:/^\d{4}-\d{2}-\d{2}$/.test(String(d.reportDate||''))?d.reportDate:TODAY(),survey_date:/^\d{4}-\d{2}-\d{2}$/.test(String(d.surveyDate||''))?d.surveyDate:null,payload:state,created_by:S.ctx.profile.user_id,updated_by:S.ctx.profile.user_id};setBusy(true);try{await OfficeDB.insert('survey_reports',row);toast('Survey report saved to Supabase.');await refresh()}catch(e){toast(errorMessage(e),'error')}finally{setBusy(false)}}
async function assignSurvey(id){if(!OfficePermissions.isAdmin())return;const assignee=$('#surveyAssignee')?.value||null;try{setBusy(true);await OfficeDB.update('survey_reports',id,{assigned_to:assignee,updated_by:S.ctx.profile.user_id});toast('Survey report access updated.');await refresh()}catch(e){toast(errorMessage(e),'error')}finally{setBusy(false)}}
function renderInvoice(){if(!canInvoice())return showView('dashboard');const docs=S.data.invoices||[],admin=OfficePermissions.isAdmin();const rows=docs.map(d=>{const a=(S.data.profiles||[]).find(p=>p.user_id===d.assigned_to);return `<tr><td>${esc(d.document_number)}</td><td>${esc(d.document_type)}</td><td>${d.document_date}</td><td>${esc(a?.display_name||'—')}</td><td class="table-actions">${admin?`<button class="btn small" data-assign-invoice="${d.id}">Assign</button>`:''}</td></tr>`});const assign=admin?`<label class="field"><span>Assign view access</span><select id="invoiceAssignee"><option value="">Not assigned — creator/company permissions</option>${employeeOptions(false).map(([v,l])=>`<option value="${esc(v)}">${esc(l)}</option>`).join('')}</select></label>`:'';const exp=has('INVOICES_EXPORT','EXPORT')?'<button class="btn" id="exportInvoices">Export CSV</button>':'';const studio=!isAdminReadOnly()?`<section class="panel"><div class="editor-launch"><div><span class="eyebrow">SAGT DOCUMENT STUDIO</span><h2>Invoice & Quotation</h2><p>Edit directly on the A4 page, generate QR and flattened PDF, then save the document model to Supabase.</p></div><button class="btn primary" id="saveInvoice">Save to Supabase</button></div></section><div class="editor-frame panel"><iframe title="Invoice Studio" src="invoice.html?v=20261005-1638" loading="lazy"></iframe></div>`:`<section class="panel"><div class="callout"><strong>Admin tracking mode:</strong> invoice content is read-only. Use Assign to give a particular employee view access, and Export for tracking data.</div></section>`;$('#view').innerHTML=pageHead('Invoice','Saved quotation / tax invoice records. Admin is tracking/export-only for document content.',`${!admin?'<button class="btn" id="openInvoice">Open Studio ↗</button>':''}${exp}`)+`<section class="panel">${assign?`<div class="form-grid">${assign}</div>`:''}<div class="saved-doc-head"><strong>Saved documents</strong><span>Only documents permitted by Supabase RLS are shown.</span></div>${table(['Document','Type','Date','Assigned employee','Action'],rows)}</section>${studio}`;$('#openInvoice')?.addEventListener('click',()=>window.open('invoice.html?v=20261005-1638','_blank','noopener'));$('#saveInvoice')?.addEventListener('click',saveInvoice);$('#exportInvoices')?.addEventListener('click',()=>exportCsv(`officeledger-invoices-${TODAY()}.csv`,['Document','Type','Date','Assigned employee'],docs.map(d=>[d.document_number,d.document_type,d.document_date,(S.data.profiles||[]).find(p=>p.user_id===d.assigned_to)?.display_name||''])));$$('[data-assign-invoice]').forEach(b=>b.onclick=()=>assignInvoice(b.dataset.assignInvoice))}
function renderSurveyReports(){if(!canSurveyReports())return showView('dashboard');const docs=S.data.survey_reports||[],admin=OfficePermissions.isAdmin();const rows=docs.map(d=>{const a=(S.data.profiles||[]).find(p=>p.user_id===d.assigned_to);return `<tr><td>${esc(d.report_number)}</td><td>${d.report_date}</td><td>${esc(a?.display_name||'—')}</td><td class="table-actions">${admin?`<button class="btn small" data-assign-survey="${d.id}">Assign</button>`:''}</td></tr>`});const assign=admin?`<label class="field"><span>Assign view access</span><select id="surveyAssignee"><option value="">Not assigned — creator/department permissions</option>${employeeOptions(false).map(([v,l])=>`<option value="${esc(v)}">${esc(l)}</option>`).join('')}</select></label>`:'';const exp=has('SURVEY_REPORTS_EXPORT','EXPORT')?'<button class="btn" id="exportSurvey">Export CSV</button>':'';const studio=!isAdminReadOnly()?`<section class="panel"><div class="editor-launch"><div><span class="eyebrow">SAGT SURVEY REPORT STUDIO</span><h2>Survey Report</h2><p>Direct A4 editing, coordinates, boundaries, QR verification and flattened PDF output.</p></div><button class="btn primary" id="saveSurvey">Save to Supabase</button></div></section><div class="editor-frame panel"><iframe title="Survey Report Studio" src="survey-report.html?v=20261005-1638" loading="lazy"></iframe></div>`:`<section class="panel"><div class="callout"><strong>Admin tracking mode:</strong> survey report content is read-only. Use Assign for employee view access and Export for tracking data.</div></section>`;$('#view').innerHTML=pageHead('Survey Reports','Saved survey report records. Admin is tracking/export-only for document content.',`${!admin?'<button class="btn" id="openSurvey">Open Studio ↗</button>':''}${exp}`)+`<section class="panel">${assign?`<div class="form-grid">${assign}</div>`:''}<div class="saved-doc-head"><strong>Saved reports</strong><span>Only reports permitted by Supabase RLS are shown.</span></div>${table(['Report No.','Report Date','Assigned employee','Action'],rows)}</section>${studio}`;$('#openSurvey')?.addEventListener('click',()=>window.open('survey-report.html?v=20261005-1638','_blank','noopener'));$('#saveSurvey')?.addEventListener('click',saveSurvey);$('#exportSurvey')?.addEventListener('click',()=>exportCsv(`officeledger-survey-reports-${TODAY()}.csv`,['Report No.','Report Date','Survey Date','Assigned employee'],docs.map(d=>[d.report_number,d.report_date,d.survey_date||'',(S.data.profiles||[]).find(p=>p.user_id===d.assigned_to)?.display_name||''])));$$('[data-assign-survey]').forEach(b=>b.onclick=()=>assignSurvey(b.dataset.assignSurvey))}
async function renderEmployees(){
 if(!OfficePermissions.isAdmin()&&!has('EMPLOYEES_VIEW','VIEW'))return showView('dashboard');
 const profiles=S.data.profiles||[], roles=S.data.roles||[], deps=S.data.departments||[], ers=S.data.employee_roles||[], eds=S.data.employee_departments||[];
 const rows=profiles.map(p=>{
   const r=ers.filter(x=>x.employee_id===p.user_id).map(x=>roles.find(y=>y.id===x.role_id)?.name).filter(Boolean).join(', ')||'—';
   const d=eds.filter(x=>x.employee_id===p.user_id&&x.is_active!==false).map(x=>deps.find(y=>y.id===x.department_id)?.name).filter(Boolean).join(', ')||'—';
   return `<tr><td>${esc(p.display_name)}</td><td>${esc(p.username||'—')}</td><td>${esc(p.email||'—')}</td><td>${esc(r)}</td><td>${esc(d)}</td><td><span class="status ${p.is_active?'present':'absent'}">${p.is_active?'ACTIVE':'INACTIVE'}</span></td><td class="table-actions"><button class="btn small" data-edit-employee="${esc(p.user_id)}">Edit</button><button class="btn small" data-reset-employee="${esc(p.user_id)}">Send reset email</button></td></tr>`;
 }).join('');
 $('#view').innerHTML=pageHead('Employees','Manage employee identity, registered email, roles, department and account status. Passwords are never visible.', '')+`<section class="panel">${table(['Employee','Username','Registered email','Roles','Department','Status','Security'],rows)}</section>`;
 $$('[data-edit-employee]').forEach(b=>b.onclick=()=>openEmployeeEditor(profiles.find(x=>x.user_id===b.dataset.editEmployee)));
 $$('[data-reset-employee]').forEach(b=>b.onclick=async()=>{try{setBusy(true);await OfficeAuth.adminEmployeeAuth('send_recovery',b.dataset.resetEmployee);toast('Password recovery email sent.')}catch(e){toast(errorMessage(e),'error')}finally{setBusy(false)}});
}
async function openEmployeeEditor(p){
 if(!p)return;
 const roles=S.data.roles||[],deps=S.data.departments||[],ers=(S.data.employee_roles||[]).filter(x=>x.employee_id===p.user_id).map(x=>x.role_id),eds=(S.data.employee_departments||[]).filter(x=>x.employee_id===p.user_id&&x.is_active!==false).map(x=>x.department_id);
 const d=$('#recordDialog');$('#recordModalTitle').textContent=`Edit employee · ${p.display_name}`;$('#recordModalSubtitle').textContent='Identity changes are audited. Passwords are reset only through Supabase Auth recovery.';
 $('#recordFields').innerHTML=`<label class="field"><span>Display name</span><input name="display_name" required maxlength="80" value="${esc(p.display_name||'')}"></label><label class="field"><span>Username</span><input name="username" required minlength="3" maxlength="32" pattern="[A-Za-z0-9._-]+" value="${esc(p.username||'')}"></label><label class="field"><span>Registered email</span><input name="email" type="email" required maxlength="254" value="${esc(p.email||'')}"></label><label class="field"><span>Phone</span><input name="phone" maxlength="30" value="${esc(p.phone||'')}"></label><label class="field"><span>Account status</span><select name="is_active"><option value="true" ${p.is_active?'selected':''}>ACTIVE</option><option value="false" ${!p.is_active?'selected':''}>INACTIVE</option></select></label><label class="field full"><span>Roles — select one or more</span><select name="role_ids" multiple size="${Math.min(roles.length,6)||1}">${roles.map(r=>`<option value="${esc(r.id)}" ${ers.includes(r.id)?'selected':''}>${esc(r.name||r.code)}</option>`).join('')}</select></label><label class="field full"><span>Primary department</span><select name="department_id"><option value="">No department</option>${deps.filter(x=>x.is_active!==false).map(x=>`<option value="${esc(x.id)}" ${eds.includes(x.id)?'selected':''}>${esc(x.name)}</option>`).join('')}</select></label><div class="callout full"><strong>Password security:</strong> The existing password cannot be viewed. Use <em>Send reset email</em> from the employee list to initiate a secure recovery.</div>`;
 $('#recordError').hidden=true;$('#recordForm').onsubmit=async e=>{e.preventDefault();try{setBusy(true);const fd=new FormData(e.currentTarget),roleIds=[...e.currentTarget.querySelector('[name="role_ids"]').selectedOptions].map(x=>x.value),departmentId=fd.get('department_id')||null;await OfficeDB.update('profiles',p.user_id,{display_name:String(fd.get('display_name')).trim(),username:OfficeAuth.validateUsername(fd.get('username')),phone:String(fd.get('phone')||'').trim(),is_active:fd.get('is_active')==='true',updated_at:new Date().toISOString()});if(String(fd.get('email')).trim().toLowerCase()!==String(p.email||'').toLowerCase())await OfficeAuth.adminEmployeeAuth('update_email',p.user_id,{email:String(fd.get('email')).trim().toLowerCase()});await OfficeDB.rpc('admin_set_employee_roles',{p_employee_id:p.user_id,p_role_ids:roleIds});const api=OfficeDB.getClient();await api.from('employee_departments').delete().eq('employee_id',p.user_id);if(departmentId)await OfficeDB.insert('employee_departments',{employee_id:p.user_id,department_id:departmentId,assigned_by:S.ctx.profile.user_id,is_primary:true,is_active:true});d.close();toast('Employee account updated.');await refresh()}catch(err){$('#recordError').textContent=errorMessage(err);$('#recordError').hidden=false}finally{setBusy(false)}};d.showModal();
}
function showPasswordSetup(mode='initial'){
 const old=$('#passwordSetupDialog');if(old)old.remove();const d=document.createElement('dialog');d.id='passwordSetupDialog';d.className='modal wide-modal';d.innerHTML=`<form class="record-form"><div class="modal-head"><div><span class="modal-eyebrow">ACCOUNT SECURITY</span><h2>${mode==='initial'?'Set Administrator Password':'Reset your password'}</h2><p>${mode==='initial'?'Your one-time bootstrap credential has been accepted. Set your permanent password now.':'Use a new OfficeLedger password that follows the security policy.'}</p></div></div><div class="modal-body"><div class="form-grid"><label class="field"><span>New password</span><input name="next" type="password" autocomplete="new-password" maxlength="8" required></label><label class="field"><span>Confirm password</span><input name="confirm" type="password" autocomplete="new-password" maxlength="8" required></label></div><small class="field-help">Exactly 6 or 8 characters · uppercase + lowercase + number + symbol · no spaces.</small><div class="form-alert" id="passwordSetupError" hidden></div><div class="modal-footer"><span class="modal-hint">Your password is handled by Supabase Auth and is never stored in OfficeLedger business tables.</span><button class="btn primary" type="submit">Set password & continue</button></div></div></form>`;document.body.appendChild(d);d.showModal();d.querySelector('form').onsubmit=async e=>{e.preventDefault();const fd=new FormData(e.currentTarget),err=d.querySelector('#passwordSetupError');err.hidden=true;try{if(fd.get('next')!==fd.get('confirm'))throw new Error('Passwords do not match.');setBusy(true);if(mode==='initial')await OfficeAuth.completeInitialPasswordSetup(fd.get('next'));else await OfficeAuth.completeRecoveryPassword(fd.get('next'));d.close();d.remove();toast('Password updated successfully.');await refresh()}catch(ex){err.textContent=errorMessage(ex);err.hidden=false}finally{setBusy(false)}};
}
async function renderSettings(){
 const p=S.ctx.profile;
 $('#view').innerHTML=pageHead('Settings','Account security and application configuration.')+`<section class="panel"><div class="panel-head"><div><strong>Account security</strong><span>Change your OfficeLedger password without storing credentials in the application database.</span></div></div><form id="passwordChangeForm" class="form-grid"><label class="field"><span>Current password</span><input name="current" type="password" autocomplete="current-password" required maxlength="8"></label><label class="field"><span>New password</span><input name="next" type="password" autocomplete="new-password" required maxlength="8"><small class="field-help">Exactly 6 or 8 characters with uppercase, lowercase, number and symbol.</small></label><label class="field"><span>Confirm new password</span><input name="confirm" type="password" autocomplete="new-password" required maxlength="8"></label><div class="form-actions"><button class="btn primary" type="submit">Change password</button></div></form><div id="passwordChangeError" class="form-alert" role="alert" hidden></div></section><section class="panel"><div class="panel-head"><div><strong>Login policy</strong><span>Username + password authentication.</span></div></div><div class="policy-chips"><span>Username: 3–32 chars</span><span>Password: 6 or 8 chars</span><span>Uppercase</span><span>Lowercase</span><span>Number</span><span>Symbol</span></div><p class="muted">Your username is stored in the employee profile for login lookup. The password itself remains exclusively under Supabase Auth.</p></section>`;
 $('#passwordChangeForm').onsubmit=async e=>{e.preventDefault();const f=new FormData(e.currentTarget),err=$('#passwordChangeError');err.hidden=true;try{if(f.get('next')!==f.get('confirm'))throw new Error('New password and confirmation do not match.');setBusy(true);await OfficeAuth.changePassword(f.get('current'),f.get('next'));e.currentTarget.reset();toast('Password changed successfully.')}catch(ex){err.textContent=errorMessage(ex);err.hidden=false}finally{setBusy(false)}};
}
async function render(){layout();const fn={dashboard:renderDashboard,employees:renderEmployees,roles:renderRoles,clients:renderClientsProjects,progress:renderProgress,attendance:renderAttendance,requests:renderRequests,expenses:renderExpenses,payroll:renderPayroll,invoice:renderInvoice,'survey-reports':renderSurveyReports,reports:renderReports,files:renderFiles,chat:renderChat,audit:renderAudit,settings:renderSettings}[S.view]||renderDashboard;await fn()}
function showView(v){if(!visibleModules().some(x=>x.id===v))v='dashboard';S.view=v;render().catch(e=>{console.error(e);toast(errorMessage(e),'error')})}
async function start(ctx){S.ctx=ctx;OfficePermissions.set(ctx);$('#authScreen').hidden=true;$('#appShell').hidden=false;await refresh();if(ctx.profile?.must_change_password)showPasswordSetup(ctx.profile.bootstrap_pending?'initial':'recovery')}
async function initialize(){try{const ctx=await OfficeAuth.restore();if(ctx)await start(ctx);else{$('#authScreen').hidden=false;$('#loginCard').hidden=false}}catch(e){$('#authScreen').hidden=false;$('#loginCard').hidden=false;$('#loginError').textContent=errorMessage(e);$('#loginError').hidden=false}}
async function login(e){e.preventDefault();const f=new FormData(e.currentTarget),btn=e.currentTarget.querySelector('button[type=submit]');btn.disabled=true;$('#loginError').hidden=true;try{await start(await OfficeAuth.login(f.get('username'),f.get('password')));e.currentTarget.reset()}catch(err){$('#loginError').textContent=errorMessage(err);$('#loginError').hidden=false}finally{btn.disabled=false}}
async function logout(){try{await OfficeAuth.logout()}finally{location.reload()}}
function bind(){document.addEventListener('click',e=>{const v=e.target.closest('[data-view]');if(v){showView(v.dataset.view);closeMobile()}});$('#loginForm').addEventListener('submit',login);$('#forgotPasswordBtn').addEventListener('click',async()=>{const identifier=prompt('Enter your OfficeLedger username or registered email:');if(!identifier)return;try{setBusy(true);await OfficeAuth.sendPasswordReset(identifier);toast('If the account is eligible, a secure password recovery email has been sent.')}catch(e){toast(errorMessage(e),'error')}finally{setBusy(false)}});$('#logoutBtn').addEventListener('click',logout);$('#mobileMenu').onclick=()=>{$('#sidebar').classList.add('open');$('#mobileShade').classList.add('show')};$('#mobileClose').onclick=closeMobile;$('#mobileShade').onclick=closeMobile;$('#globalSearch').oninput=e=>{const q=e.target.value.toLowerCase().trim();$$('.module-card').forEach(c=>c.hidden=q&&!c.textContent.toLowerCase().includes(q))}}
function closeMobile(){$('#sidebar').classList.remove('open');$('#mobileShade').classList.remove('show')}
window.addEventListener('message',e=>{if(e.origin===location.origin&&e.data?.type==='OFFICELEDGER_DOCUMENT_SAVE')saveInvoice()});window.addEventListener('error',e=>{if(e?.error?.message&&/rows_join/i.test(e.error.message))toast('A stale OfficeLedger script was detected. Please refresh with the current package.','error');});window.addEventListener('unhandledrejection',e=>{if(e?.reason?.message&&/rows_join/i.test(e.reason.message))toast('A stale OfficeLedger script was detected. Please refresh with the current package.','error');});document.addEventListener('DOMContentLoaded',()=>{bind();initialize()});
})();
