/* Shared report builders and dependency-free CSV/XLSX exports. */
(function(){
  'use strict';
  const A=()=>OfficeAccounting;
  function usersById(users,id){return users.find(u=>u.id===id);}
  function eventRows(records,users){return A().cleanRecords(records).map(r=>A().buildLedgerRow(r,users,records)).sort((a,b)=>b.date.localeCompare(a.date));}
  function report(type,{records,users,settings,month,employeeId,from,to}){
    const active=A().cleanRecords(records);let rows=[],headers=[],title='Expense report';
    const inRange=r=>{const d=A().recordPeriodDate(r);return (!from||d>=from)&&(!to||d<=to);};
    if(type==='monthly'){
      title='Monthly accounting report';const m=A().monthlySummary(active,month);headers=['Category','Monthly total'];rows=A().CATEGORIES.map(c=>[c.name,m.byCategory[c.id]||0]);rows.push(['Total expenses',m.totalExpenses],['Total refunds',m.refunded],['Net office expenses',m.netOfficeExpenses],['Pending client reimbursements',m.pendingReimbursements]);
    }else if(type==='clients'){
      title='Client expense report';headers=['Date','Transaction ID','Client','Project','Expense type','Paid by','Reimbursable','Expense','Refunded','Outstanding','Status'];rows=active.filter(r=>r.category==='Client Expenses'&&inRange(r)).map(r=>{const refunded=A().refundTotalFor(r.id,active);return [r.date,r.transactionId||r.id,r.client||'',r.project||'',r.expenseType||'',r.paidBy||'',r.reimbursable?'Yes':'No',Number(r.amount)||0,refunded,A().outstandingForClientExpense(r,active),r.status||'Paid'];});
    }else if(type==='petty'){
      title='Petty cash report';headers=['Date','Transaction ID','Movement','Transaction category','Description','Person responsible','Cash received','Cash spent','Balance'];const all=active.filter(r=>r.category==='Petty Cash').sort((a,b)=>a.date.localeCompare(b.date));const p=all.filter(inRange);let balance=(Number(settings.openingPettyCash)||0)+all.filter(r=>from&&r.date<from).reduce((sum,r)=>sum+(r.cashDirection==='Received'?1:-1)*(Number(r.amount)||0),0);rows=[['','Opening balance','','','','','', '',balance]];for(const r of p){const received=r.cashDirection==='Received'?Number(r.amount)||0:0,spent=r.cashDirection==='Spent'?Number(r.amount)||0:0;balance+=received-spent;rows.push([r.date,r.transactionId||r.id,r.cashDirection,r.subcategory||'',r.description||r.remarks||'',r.person||r.employeeName||'',received,spent,balance]);}rows.push(['','','Closing balance','','','','','',balance]);
    }else if(type==='salary'){
      title='Salary report';headers=['Salary month','Employee','Gross salary','Deductions','Net salary','Payment date','Status','Payment method','Reference'];rows=active.filter(r=>r.category==='Salaries'&&(!month||r.salaryMonth===month)&&inRange(r)).map(r=>[r.salaryMonth||'',r.employeeName||'',Number(r.grossSalary)||0,Number(r.deductions)||0,Number(r.amount)||0,r.paymentDate||r.date||'',r.status||'',r.paymentMethod||'',r.referenceNumber||'']);
    }else if(type==='maintenance'){
      title='Office maintenance report';const cats=['Rent','Electricity','Wi-Fi','Flat Maintenance','Washroom Cleaning','Drinking Water Supply','Cleaner Expenses & Maintenance','Tea Maker Expenses & Maintenance'];headers=['Date','Transaction ID','Category','Vendor / person','Description','Amount','Payment method','Reference','Remarks','Created by'];rows=active.filter(r=>cats.includes(r.category)&&inRange(r)).map(r=>[r.date,r.transactionId||r.id,r.category,r.vendor||r.payee||r.person||'',r.description||'',Number(r.amount)||0,r.paymentMethod||'',r.referenceNumber||'',r.remarks||'',usersById(users,r.createdBy)?.name||'']);
    }else if(type==='employee'){
      title='Employee entry report';headers=['Date','Transaction ID','Category','Description','Amount','Created by','Last updated by','Last updated'];rows=active.filter(r=>(r.createdBy===employeeId||r.updatedBy===employeeId)&&inRange(r)).map(r=>[r.date,r.transactionId||r.id,r.category,r.description||'',Number(r.amount)||0,usersById(users,r.createdBy)?.name||'',usersById(users,r.updatedBy)?.name||'',r.updatedAt||'']);
    }else{
      title='Expense report';headers=['Date','Transaction ID','Category','Description','Debit','Credit','Payment method','Reference','Employee','Client','Project','Vendor','Status'];rows=eventRows(active,users).filter(r=>inRange(r.record)).map(r=>[r.date,r.id,r.category,r.description,r.debit,r.credit,r.paymentMethod,r.reference,r.employee,r.client,r.project,r.vendor,r.status]);
    }
    return {title,headers,rows,month,from,to};
  }
  function categoryBreakdown(records,month){return A().CATEGORIES.map(c=>({category:c.id,total:A().totalForCategory(records,c.id,month)}));}
  function csvEscape(value){let s=value==null?'':String(value);if(/^[=+@\-]/.test(s)&&isNaN(Number(s)))s="'"+s;return `"${s.replace(/"/g,'""')}"`;}
  function download(blob,name){const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),1200);}
  function exportCSV(data){const lines=[data.headers,...data.rows].map(row=>row.map(csvEscape).join(',')).join('\r\n');download(new Blob(['\ufeff',lines],{type:'text/csv;charset=utf-8'}),`officeledger-${data.title.toLowerCase().replace(/[^a-z0-9]+/g,'-')}.csv`);}
  function xmlEscape(v){return String(v??'').replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;').replace(/'/g,'&apos;');}
  function colName(n){let s='';for(n++;n;n=Math.floor((n-1)/26))s=String.fromCharCode(65+(n-1)%26)+s;return s;}
  function crc32(data){let crc=-1;for(const b of data){crc^=b;for(let k=0;k<8;k++)crc=(crc>>>1)^((crc&1)?0xEDB88320:0);}return (crc^-1)>>>0;}
  const u16=n=>[n&255,(n>>>8)&255],u32=n=>[n&255,(n>>>8)&255,(n>>>16)&255,(n>>>24)&255];
  function zipStored(files){const enc=new TextEncoder(),local=[],central=[];let offset=0;const d=new Date(),time=(d.getHours()<<11)|(d.getMinutes()<<5)|Math.floor(d.getSeconds()/2),date=((Math.max(1980,d.getFullYear())-1980)<<9)|((d.getMonth()+1)<<5)|d.getDate();for(const [name,content]of files){const n=enc.encode(name),data=typeof content==='string'?enc.encode(content):content,crc=crc32(data);const h=[0x50,0x4b,3,4,...u16(20),...u16(0),...u16(0),...u16(time),...u16(date),...u32(crc),...u32(data.length),...u32(data.length),...u16(n.length),...u16(0)];local.push(new Uint8Array([...h,...n,...data]));const c=[0x50,0x4b,1,2,...u16(20),...u16(20),...u16(0),...u16(0),...u16(time),...u16(date),...u32(crc),...u32(data.length),...u32(data.length),...u16(n.length),...u16(0),...u16(0),...u16(0),...u16(0),...u32(0),...u32(offset)];central.push(new Uint8Array([...c,...n]));offset+=h.length+n.length+data.length;}const csize=central.reduce((s,x)=>s+x.length,0),end=new Uint8Array([0x50,0x4b,5,6,...u16(0),...u16(0),...u16(files.length),...u16(files.length),...u32(csize),...u32(offset),...u16(0)]);return new Blob([...local,...central,end],{type:'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'});}
  function worksheet(rows){const widths=Array.from({length:Math.max(1,...rows.map(r=>r.length))},(_,ci)=>Math.min(38,Math.max(12,...rows.map(r=>String(r[ci]??'').length+2))));const cols=`<cols>${widths.map((w,i)=>`<col min="${i+1}" max="${i+1}" width="${w}" customWidth="1"/>`).join('')}</cols>`;const data=rows.map((row,ri)=>`<row r="${ri+1}">${row.map((v,ci)=>{if(v===null||v===undefined||v==='')return '';const ref=`${colName(ci)}${ri+1}`;const style=ri===0?' s="1"':'';if(typeof v==='number'&&Number.isFinite(v))return `<c r="${ref}"${style}><v>${v}</v></c>`;return `<c r="${ref}"${style} t="inlineStr"><is><t xml:space="preserve">${xmlEscape(v)}</t></is></c>`;}).join('')}</row>`).join('');return `<?xml version="1.0" encoding="UTF-8" standalone="yes"?><worksheet xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main"><sheetViews><sheetView showGridLines="0"><pane ySplit="1" topLeftCell="A2" activePane="bottomLeft" state="frozen"/></sheetView></sheetViews>${cols}<sheetData>${data}</sheetData></worksheet>`;}
  function exportExcel({records,users,settings,month}){
    const ledger=eventRows(records,users);const monthReport=report('monthly',{records,users,settings,month});const clientReport=report('clients',{records,users,settings,month});const pettyReport=report('petty',{records,users,settings,month});const salaryReport=report('salary',{records,users,settings,month});const maintenanceReport=report('maintenance',{records,users,settings,month});
    const sheets=[['Monthly summary',[['Category','Monthly total'],...monthReport.rows]],['Ledger',[['Date','Transaction ID','Category','Description','Debit','Credit','Payment method','Reference','Created by','Status'],...ledger.map(r=>[r.date,r.id,r.category,r.description,r.debit,r.credit,r.paymentMethod,r.reference,r.createdBy,r.status])]],['Client expenses',[clientReport.headers,...clientReport.rows]],['Petty cash',[pettyReport.headers,...pettyReport.rows]],['Salaries',[salaryReport.headers,...salaryReport.rows]],['Maintenance',[maintenanceReport.headers,...maintenanceReport.rows]]];
    const content=sheets.map((_,i)=>`<Override PartName="/xl/worksheets/sheet${i+1}.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.worksheet+xml"/>`).join('');const names=sheets.map(([n],i)=>`<sheet name="${xmlEscape(n)}" sheetId="${i+1}" r:id="rId${i+1}"/>`).join('');const rels=sheets.map((_,i)=>`<Relationship Id="rId${i+1}" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/worksheet" Target="worksheets/sheet${i+1}.xml"/>`).join('')+`<Relationship Id="rId${sheets.length+1}" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/styles" Target="styles.xml"/>`;
    const styles='<?xml version="1.0" encoding="UTF-8" standalone="yes"?><styleSheet xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main"><fonts count="2"><font><sz val="10"/><name val="Arial"/></font><font><b/><sz val="10"/><color rgb="FF1B302B"/><name val="Arial"/></font></fonts><fills count="1"><fill><patternFill patternType="none"/></fill></fills><borders count="1"><border><left/><right/><top/><bottom/><diagonal/></border></borders><cellStyleXfs count="1"><xf numFmtId="0" fontId="0" fillId="0" borderId="0"/></cellStyleXfs><cellXfs count="2"><xf numFmtId="0" fontId="0" fillId="0" borderId="0"/><xf numFmtId="0" fontId="1" fillId="0" borderId="0" applyFont="1"/></cellXfs><cellStyles count="1"><cellStyle name="Normal" xfId="0" builtinId="0"/></cellStyles></styleSheet>';
    const files=[['[Content_Types].xml',`<?xml version="1.0" encoding="UTF-8" standalone="yes"?><Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types"><Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/><Default Extension="xml" ContentType="application/xml"/><Override PartName="/xl/workbook.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet.main+xml"/><Override PartName="/xl/styles.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.styles+xml"/>${content}</Types>`],['_rels/.rels','<?xml version="1.0" encoding="UTF-8" standalone="yes"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument" Target="xl/workbook.xml"/></Relationships>'],['xl/workbook.xml',`<?xml version="1.0" encoding="UTF-8" standalone="yes"?><workbook xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main" xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships"><sheets>${names}</sheets></workbook>`],['xl/_rels/workbook.xml.rels',`<?xml version="1.0" encoding="UTF-8" standalone="yes"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships">${rels}</Relationships>`],['xl/styles.xml',styles],...sheets.map(([,rows],i)=>[`xl/worksheets/sheet${i+1}.xml`,worksheet(rows)])];download(zipStored(files),`officeledger-${month||A().today()}.xlsx`);
  }
  window.OfficeReports={report,categoryBreakdown,eventRows,exportCSV,exportExcel};
})();
