-- OfficeLedger username login and password policy metadata.
-- Supabase Auth remains the credential authority; plaintext passwords are never stored here.
alter table public.profiles add column if not exists username text;
update public.profiles set username=lower(regexp_replace(coalesce(nullif(display_name,''),split_part(email,'@',1)),'[^a-zA-Z0-9._-]','','g')) where username is null or btrim(username)='';
update public.profiles p set username=lower(split_part(p.email,'@',1)) where exists(select 1 from public.profiles x where x.user_id<>p.user_id and x.username=p.username);
alter table public.profiles alter column username set not null;
create unique index if not exists profiles_username_lower_uidx on public.profiles(lower(username));
create table if not exists public.auth_password_policy(id boolean primary key default true check(id),allowed_lengths integer[] not null default array[6,8],require_upper boolean not null default true,require_lower boolean not null default true,require_number boolean not null default true,require_symbol boolean not null default true,allow_spaces boolean not null default false,updated_at timestamptz not null default now(),constraint auth_password_policy_lengths check(allowed_lengths <@ array[6,8]::integer[] and cardinality(allowed_lengths)>0));
insert into public.auth_password_policy(id,allowed_lengths,require_upper,require_lower,require_number,require_symbol,allow_spaces) values(true,array[6,8],true,true,true,true,false) on conflict(id) do update set allowed_lengths=excluded.allowed_lengths,require_upper=excluded.require_upper,require_lower=excluded.require_lower,require_number=excluded.require_number,require_symbol=excluded.require_symbol,allow_spaces=excluded.allow_spaces,updated_at=now();
alter table public.auth_password_policy enable row level security;
drop policy if exists auth_password_policy_select on public.auth_password_policy;
create policy auth_password_policy_select on public.auth_password_policy for select to anon,authenticated using(true);
create or replace function public.get_auth_login_policy() returns jsonb language sql stable security invoker set search_path=public as $$ select jsonb_build_object('username_login',true,'password_lengths',allowed_lengths,'require_upper',require_upper,'require_lower',require_lower,'require_number',require_number,'require_symbol',require_symbol,'allow_spaces',allow_spaces) from public.auth_password_policy where id=true; $$;
revoke all on function public.get_auth_login_policy() from public; grant execute on function public.get_auth_login_policy() to anon,authenticated;
create or replace function public.resolve_login_username(p_username text) returns text language plpgsql security definer set search_path=public as $$ declare v_email text; begin if p_username is null or btrim(p_username)='' then return null; end if; select p.email into v_email from public.profiles p where lower(p.username)=lower(btrim(p_username)) and p.is_active=true limit 1; return v_email; end; $$;
revoke all on function public.resolve_login_username(text) from public; grant execute on function public.resolve_login_username(text) to anon,authenticated;
create or replace function app_private.username_format_guard() returns trigger language plpgsql as $$ begin new.username=lower(btrim(new.username)); if new.username !~ '^[a-z0-9][a-z0-9._-]{2,31}$' then raise exception 'Username must be 3-32 characters and use only letters, numbers, dot, underscore or hyphen.'; end if; return new; end; $$;
drop trigger if exists trg_profiles_username_format on public.profiles; create trigger trg_profiles_username_format before insert or update of username on public.profiles for each row execute function app_private.username_format_guard();
create or replace function app_private.password_meets_policy(p_password text) returns boolean language sql stable as $$ select p_password is not null and exists(select 1 from public.auth_password_policy ap where ap.id=true and length(p_password)=any(ap.allowed_lengths) and (ap.allow_spaces or p_password !~ '\s') and ((not ap.require_upper) or p_password ~ '[A-Z]') and ((not ap.require_lower) or p_password ~ '[a-z]') and ((not ap.require_number) or p_password ~ '[0-9]') and ((not ap.require_symbol) or p_password ~ '[^A-Za-z0-9\s]')); $$;
update public.profiles set password_changed_at=coalesce(password_changed_at,created_at);
comment on column public.profiles.username is 'OfficeLedger login username; authentication credential remains in Supabase Auth.';
comment on table public.auth_password_policy is 'Application password policy metadata. Supabase Auth remains the credential authority; plaintext passwords are never stored here.';
